export const authConstants= {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export const userContants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  }

  export const dataConstants = {
    GET_ALL_DATA_REQUEST: "GET_ALL_DATA_REQUEST",
    GET_ALL_DATA_SUCCESS: "GET_ALL_DATA_SUCCESS",
    GET_ALL_DATA_FAILURE: "GET_ALL_DATA_FAILURE",
    ADD_NEW_DATA_REQUEST: "ADD_NEW_DATA_REQUEST",
    ADD_NEW_DATA_SUCCESS: "ADD_NEW_DATA_SUCCESS",
    ADD_NEW_DATA_FAILURE: "ADD_NEW_DATA_FAILURE",
    UPDATE_DATA_REQUEST: "UPDATE_DATA_REQUEST",
    UPDATE_DATA_SUCCESS: "UPDATE_DATA_SUCCESS",
    UPDATE_DATA_FAILURE: "UPDATE_DATA_FAILURE",
    DELETE_DATA_REQUEST: "DELETE_DATA_REQUEST",
    DELETE_DATA_SUCCESS: "DELETE_DATA_SUCCESS",
    DELETE_DATA_FAILURE: "DELETE_DATA_FAILURE",
  }